version: '2'

services:

    nginx:
        restart: always
        image: nginx

    database:
        restart: always
        image: postgres:9.5
        expose:
            - 5432
        volumes:
          - ./postgres/data:/var/lib/postgresql

    webserver:
        restart: always
        build:
            context: .
            dockerfile: ./compose/django/Dockerfile
        volumes:
            - .:/app

    web:
        restart: always
        build:
            context: .
            dockerfile: ./compose/web/Dockerfile
        volumes:
            - .:/app
