version: '2'

services:

    database:
        extends:
          file: ./common.yml
          service: database
        env_file:
          - ./docker/environ/local
        ports:
          - 5433:5432

    backend:
        extends:
          file: ./common.yml
          service: backend
        links:
          - database
        entrypoint:
          - /django-entrypoint.sh
        env_file:
          - ./docker/environ/local
        ports:
          - 8000:8000

    frontend:
        extends:
          file: ./common.yml
          service: frontend
        links:
          - backend
        environment:
          - NODE_ENV=development
        ports:
          - 3000:3000
