version: '2'

services:

    database:
        extends:
          file: ./docker/common.yml
          service: database
        env_file:
          - ./docker/environ/local
        ports:
          - 5433:5432

    pgadmin:
        image: thajeztah/pgadmin4
        container_name: pgadmin
        links:
          - database
        ports:
          - 5050:5050

    webserver:
        extends:
          file: ./docker/common.yml
          service: webserver
        links:
          - database
        entrypoint:
          - /django-entrypoint.sh
        env_file:
          - ./docker/environ/local
        ports:
          - 8000:8000

    frontend:
        extends:
          file: ./docker/common.yml
          service: frontend
        links:
          - webserver
        environment:
          - NODE_ENV=development
        ports:
          - 3000:3000
