version: '2'

services:

    nginx:
        extends:
            file: ./common.yml
            service: nginx
        ports:
            - 8000:8000
        volumes:
            - ./compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - webserver

    database:
        extends:
            file: ./common.yml
            service: database
        ports:
            - 5433:5432

    webserver:
        extends:
            file: ./common.yml
            service: webserver
        links:
            - database
        entrypoint:
            - /django-entrypoint.sh
        expose:
            - 8000

    frontend:
        extends:
            file: ./common.yml
            service: web
        links:
            - webserver
        entrypoint:
            - /web-entrypoint.sh
