version: '2'

services:

    nginx:
        restart: always
        image: nginx

    database:
        restart: always
        image: postgres:9.5
        expose:
            - 5432
        volumes:
          - ./docker/postgres/data:/var/lib/postgresql

    webserver:
        restart: always
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        volumes:
            - .:/django

    web:
        restart: always
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - .:/django
