version: '2'

services:

    nginx:
      restart: always
      image: nginx

    database:
      container_name: database
      restart: always
      image: postgres:9.5
      expose:
        - 5432
